apiVersion: v1
kind: Service
metadata:
  name: cache-worker
  labels:
    app: cache-worker
spec:
  ports:
    - port: 80
  selector:
    app: cache-worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache-worker
  labels:
    app: cache-worker
spec:
  replicas: 5
  serviceName: "cache-worker"
  minReadySeconds: 20
  selector:
    matchLabels:
      app: cache-worker
  template:
    metadata:
      labels:
        app: cache-worker
    spec:
      containers:
        - name: cache-worker
          image: cache-worker:latest
          imagePullPolicy: Never
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            failureThreshold: 10
            periodSeconds: 10
          env:
            - name: ZOO_KEEPER
              value: "zk-cs.default.svc.cluster.local"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
