apiVersion: v1
kind: Service
metadata:
  name: cache-server
  labels:
    app: cache-server
spec:
  ports:
    - port: 80
  selector:
    app: cache-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
  labels:
    app: cache-server
spec:
  replicas: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      app: cache-server
  template:
    metadata:
      labels:
        app: cache-server
    spec:
      containers:
        - name: cache-server
          image: cache-server:latest
          imagePullPolicy: Never
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            failureThreshold: 10
            periodSeconds: 10
          env:
            - name: ZOO_KEEPER
              value: "zk-cs.default.svc.cluster.local"
            - name: WORKER_RING_REPLICAS
              value: "50"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
